name: Build enrollment-server

on:
  push:
    branches: [ main ]
    paths:
      - "lighthouse/enrollment-server/**"
      - "common/influx_client"

jobs:
  enrollment-server:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nnandrew
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/build-push-action@v5
        with:
          context: ./lighthouse/enrollment-server
          file: ./lighthouse/enrollment-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/nnandrew/polaris/enrollment-server:latest