name: Build ntrip-caster

on:
  push:
    branches: [ main ]
    paths:
      - "base-station/ntrip-caster/**"
      - "common/**"

jobs:
  ntrip-caster:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nnandrew
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/build-push-action@v5
        with:
          context: ./base-station/ntrip-caster
          file: ./base-station/ntrip-caster/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/nnandrew/polaris/ntrip-caster:latest