name: Build ntrip-client

on:
  push:
    branches: [ main ]
    paths:
      - "rover/ntrip-client/**"
      - "common/**"

jobs:
  ntrip-client:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nnandrew
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/build-push-action@v5
        with:
          context: ./rover/ntrip-client
          file: ./rover/ntrip-client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/nnandrew/polaris/ntrip-client:latest