name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - "common/**"
      - "lighthouse/enrollment-server/**"
      - "rover/ntrip-client/**"
      - "base-station/ntrip-caster/**"
      - ".github/workflows/docker.yml"

jobs:
  enrollment-client:
    name: Build enrollment-client
    runs-on: ubuntu-latest
    permissions: write-all
    # Run only if enrollment-client files changed
    if: |
      contains(join(fromJson(toJson(github.event.commits)).*.modified), 'common/enrollment-client/')
      || contains(join(fromJson(toJson(github.event.commits)).*.added), 'common/enrollment-client/')
      || contains(join(fromJson(toJson(github.event.commits)).*.removed), 'common/enrollment-client/')
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nnandrew
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v5
        with:
          context: ./common/enrollment-client
          file: ./common/enrollment-client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/nnandrew/polaris/enrollment-client:latest

  enrollment-server:
    name: Build enrollment-server
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      contains(join(fromJson(toJson(github.event.commits)).*.modified), 'lighthouse/enrollment-server/')
      || contains(join(fromJson(toJson(github.event.commits)).*.added), 'lighthouse/enrollment-server/')
      || contains(join(fromJson(toJson(github.event.commits)).*.removed), 'lighthouse/enrollment-server/')
      || contains(join(fromJson(toJson(github.event.commits)).*.modified), 'common/influx_client')
      || contains(join(fromJson(toJson(github.event.commits)).*.added), 'common/influx_client')
      || contains(join(fromJson(toJson(github.event.commits)).*.removed), 'common/influx_client')
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nnandrew
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v5
        with:
          context: ./lighthouse/enrollment-server
          file: ./lighthouse/enrollment-server/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/nnandrew/polaris/enrollment-server:latest

  ntrip-client:
    name: Build ntrip-client
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      contains(join(fromJson(toJson(github.event.commits)).*.modified), 'rover/ntrip-client/')
      || contains(join(fromJson(toJson(github.event.commits)).*.added), 'rover/ntrip-client/')
      || contains(join(fromJson(toJson(github.event.commits)).*.removed), 'rover/ntrip-client/')
      || contains(join(fromJson(toJson(github.event.commits)).*.modified), 'common/')
      || contains(join(fromJson(toJson(github.event.commits)).*.added), 'common/')
      || contains(join(fromJson(toJson(github.event.commits)).*.removed), 'common/')
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nnandrew
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v5
        with:
          context: ./rover/ntrip-client
          file: ./rover/ntrip-client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/nnandrew/polaris/ntrip-client:latest

  ntrip-caster:
    name: Build ntrip-caster
    runs-on: ubuntu-latest
    permissions: write-all
    if: |
      contains(join(fromJson(toJson(github.event.commits)).*.modified), 'base-station/ntrip-caster/')
      || contains(join(fromJson(toJson(github.event.commits)).*.added), 'base-station/ntrip-caster/')
      || contains(join(fromJson(toJson(github.event.commits)).*.removed), 'base-station/ntrip-caster/')
      || contains(join(fromJson(toJson(github.event.commits)).*.modified), 'common/')
      || contains(join(fromJson(toJson(github.event.commits)).*.added), 'common/')
      || contains(join(fromJson(toJson(github.event.commits)).*.removed), 'common/')
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nnandrew
          password: ${{ secrets.GHCR_PAT }}
      - uses: docker/build-push-action@v5
        with:
          context: ./base-station/ntrip-caster
          file: ./base-station/ntrip-caster/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/nnandrew/polaris/ntrip-caster:latest