name: Build enrollment-client

on:
  push:
    branches: [ main ]
    paths:
      - "common/enrollment-client/**"

jobs:
  enrollment-client:
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: nnandrew
          password: ${{ secrets.GHCR_PAT }}

      - uses: docker/build-push-action@v5
        with:
          context: ./common/enrollment-client
          file: ./common/enrollment-client/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ghcr.io/nnandrew/polaris/enrollment-client:latest